Description:
  VPC With 3 subnets

Parameters:

  VpcCIDR:
    Description: VPC CIDR IP
    Type: String
    Default: 10.192.0.0/16

  Subnet1CIDR:
    Description: First Availability Zone CIDR Range
    Type: String
    Default: 10.192.10.0/24

  Subnet2CIDR:
    Description: Second Availability Zone CIDR Range
    Type: String
    Default: 10.192.11.0/24

  Subnet3CIDR:
    Description: Third Availability Zone CIDR Range
    Type: String
    Default: 10.192.20.0/24

  Region:
    Description: Enter region.
    Type: String
    Default: us-east-1

  AMI:
    Description: "AMI for Instance"
    Type: String

  KeyName:
    Description: "Key Name for Instance"
    Type: String



Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-IGW

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref Subnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PubSub1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Ref Subnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PubSub2

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: !Ref Subnet3CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PubSub3

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PRT

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PublicSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet3

  application:
   Type: 'AWS::EC2::SecurityGroup'
   Properties:
      GroupDescription: Base Security Group
      SecurityGroupIngress:
         - IpProtocol: tcp
           CidrIp: 0.0.0.0/0
           FromPort: 22
           ToPort: 22
         - IpProtocol: tcp
           CidrIp: 0.0.0.0/0
           FromPort: 80
           ToPort: 80
         - IpProtocol: tcp
           CidrIp: 0.0.0.0/0
           FromPort: 443
           ToPort: 443
         - IpProtocol: tcp
           CidrIp: 0.0.0.0/0
           FromPort: 8081
           ToPort: 8081
      VpcId: !Ref VPC 
  Ec2Instance: 
   Type: AWS::EC2::Instance
   Properties: 
    ImageId: !Ref AMI
    KeyName: !Ref KeyName
    InstanceType: "t2.micro"
    BlockDeviceMappings: 
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "20"
    NetworkInterfaces:
      - AssociatePublicIpAddress: "true"
        DeleteOnTermination: "true"
        SubnetId: !Ref PublicSubnet1
        DeviceIndex: "0"
        GroupSet:
         - !Ref application
    Outputs:
        VpcId:
          Description: The VPC ID
          Value: !Ref VPC
        SubnetId1:
          Description: The Subnet ID 1
          Value: !Ref PublicSubnet1
        SubnetId2:
          Description: The Subnet ID 2
          Value: !Ref PublicSubnet2
        SubnetId3:
          Description: The Subnet ID 3
          Value: !Ref PublicSubnet3
        InternetGateway:
          Description: Internet Gateway
          Value: !Ref InternetGateway
        Route:
          Description: Route
          Value: !Ref myRoute
        RouteTable:
          Description: Route Table
          Value: !Ref PublicRouteTable